In [4]:
import pandas as pd

# workin with json

In [5]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [6]:
df = pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')
df

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-14,1773446402,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-14,1773446402,0.0397
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-14,1773446402,0.6860
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-14,1773446402,0.9030
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-14,1773446402,4.0900
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-14,1773446402,2.5900
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-14,1773446402,0.1820
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-14,1773446402,0.2110
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-14,1773446402,0.2750
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-03-14,1773446402,0.2750

# working with sql

In [10]:
!pip install mysql.connector

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql.connector in C:\Users\yadav\AppData\Roaming\Python\Python311\site-packages (2.2.9)

In [12]:
import mysql.connector

In [13]:
mysql.connector.connect(host= 'localhost',user= 'root',password='',database='world')

In [23]:
#df = pd.read_sql_query("SELECT * FROM city WHERE CountryCode LIKE 'USA'",'con')
con = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="world"
)

# read SQL query
df = pd.read_sql_query(
    "SELECT * FROM city WHERE CountryCode LIKE 'USA'",
    con
)

print(df.head())

     ID          Name CountryCode      District  Population
0  3793      New York         USA      New York     8008278
1  3794   Los Angeles         USA    California     3694820
2  3795       Chicago         USA      Illinois     2896016
3  3796       Houston         USA         Texas     1953631
4  3797  Philadelphia         USA  Pennsylvania     1517550

C:\Users\yadav\AppData\Local\Temp\ipykernel_22824\3342748318.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(